FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --silent

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN sed -i 's/\r$//' /usr/local/bin/docker-entrypoint.sh && chmod +x /usr/local/bin/docker-entrypoint.sh

EXPOSE 5173

CMD ["/usr/local/bin/docker-entrypoint.sh"]