controls_seed = [
    {
            "nombre": "ISO 27001 - 5.1 Políticas para la seguridad de la información",
            "descripcion": "Políticas para la seguridad de la información",
            "dimensiones": 1,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 5.2 Roles y responsabilidades de seguridad de la información",
            "descripcion": "Roles y responsabilidades de seguridad de la información",
            "dimensiones": 1,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 5.3 Segregación de funciones",
            "descripcion": "Segregación de funciones",
            "dimensiones": 1,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 5.4 Responsabilidades de la dirección",
            "descripcion": "Responsabilidades de la dirección",
            "dimensiones": 1,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 5.5 Contacto con las autoridades",
            "descripcion": "Contacto con las autoridades",
            "dimensiones": 1,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 5.6 Contacto con grupos de interés especial",
            "descripcion": "Contacto con grupos de interés especial",
            "dimensiones": 1,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 5.7 Inteligencia de amenazas",
            "descripcion": "Inteligencia de amenazas",
            "dimensiones": 1,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 5.8 Seguridad de la información en la gestión de proyectos",
            "descripcion": "Seguridad de la información en la gestión de proyectos",
            "dimensiones": 1,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 6.1 Investigación de antecedentes",
            "descripcion": "Investigación de antecedentes",
            "dimensiones": 2,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 6.2 Términos y condiciones de empleo",
            "descripcion": "Términos y condiciones de empleo",
            "dimensiones": 2,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 6.3 Concienciación, educación y formación en seguridad de la información",
            "descripcion": "Concienciación, educación y formación en seguridad de la información",
            "dimensiones": 2,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 6.4 Proceso disciplinario",
            "descripcion": "Proceso disciplinario",
            "dimensiones": 2,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 7.1 Perímetros de seguridad física",
            "descripcion": "Perímetros de seguridad física",
            "dimensiones": 3,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 7.2 Controles físicos de entrada",
            "descripcion": "Controles físicos de entrada",
            "dimensiones": 3,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 7.3 Seguridad de oficinas, despachos e instalaciones",
            "descripcion": "Seguridad de oficinas, despachos e instalaciones",
            "dimensiones": 3,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 7.4 Supervisión de la seguridad física",
            "descripcion": "Supervisión de la seguridad física",
            "dimensiones": 3,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 8.1 Dispositivos de usuario final",
            "descripcion": "Dispositivos de usuario final",
            "dimensiones": 4,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 8.2 Derechos de acceso privilegiado",
            "descripcion": "Derechos de acceso privilegiado",
            "dimensiones": 4,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 8.3 Restricción de acceso a la información",
            "descripcion": "Restricción de acceso a la información",
            "dimensiones": 4,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 8.4 Acceso al código fuente",
            "descripcion": "Acceso al código fuente",
            "dimensiones": 4,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 8.5 Autenticación segura",
            "descripcion": "Autenticación segura",
            "dimensiones": 4,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 8.6 Gestión de capacidad",
            "descripcion": "Gestión de capacidad",
            "dimensiones": 4,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 8.7 Protección contra malware",
            "descripcion": "Protección contra malware",
            "dimensiones": 4,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
        {
            "nombre": "ISO 27001 - 8.8 Gestión de vulnerabilidades técnicas",
            "descripcion": "Gestión de vulnerabilidades técnicas",
            "dimensiones": 4,
            "activo": True,
            "confidencialidad": True,
            "integridad": True,
            "disponibilidad": True,
            "rec_alta": "Implementar medidas correctivas inmediatas.",
            "rec_media": "Mejorar los controles existentes.",
            "rec_baja": "Monitorear periódicamente.",
        },
    ]
