# ============================================================
# ISO 27001:2022 – Controles de Seguridad de la Información
# Banco de preguntas alineadas a los 93 controles del Anexo A
# ============================================================

controls_seed = [
    # ── CATEGORÍA 5: CONTROLES ORGANIZACIONALES ──────────────
    {
        "nombre": "ISO 27001 - 5.1 Políticas para la seguridad de la información",
        "descripcion": "Definición, aprobación y comunicación de las políticas de seguridad de la información.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Redactar, aprobar y socializar formalmente la política de seguridad con toda la organización.",
        "rec_media": "Revisar y actualizar las políticas existentes para alinearlas con la ISO 27001:2022.",
        "rec_baja": "Mantener ciclos de revisión periódicos y documentar las aprobaciones de la dirección.",
    },
    {
        "nombre": "ISO 27001 - 5.2 Roles y responsabilidades de seguridad de la información",
        "descripcion": "Asignación y comunicación de roles y responsabilidades de seguridad.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Definir formalmente roles de seguridad con perfiles de puesto documentados.",
        "rec_media": "Actualizar las descripciones de cargo para incluir obligaciones de seguridad.",
        "rec_baja": "Revisar anualmente la pertinencia de los roles asignados.",
    },
    {
        "nombre": "ISO 27001 - 5.3 Segregación de funciones",
        "descripcion": "Separación de funciones incompatibles para reducir el riesgo de fraude o error.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": False,
        "rec_alta": "Implementar controles de acceso que impidan que un solo individuo realice tareas críticas sin supervisión.",
        "rec_media": "Mapear y documentar las funciones incompatibles e implementar controles compensatorios.",
        "rec_baja": "Revisar periodicamente la matriz de segregación de funciones.",
    },
    {
        "nombre": "ISO 27001 - 5.4 Responsabilidades de la dirección",
        "descripcion": "Compromiso activo de la alta dirección con la seguridad de la información.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Establecer un comité de seguridad con participación directiva y agenda formal.",
        "rec_media": "Documentar el respaldo de la dirección mediante actas y comunicaciones formales.",
        "rec_baja": "Mantener métricas de seguridad visibles para la alta dirección.",
    },
    {
        "nombre": "ISO 27001 - 5.5 Contacto con las autoridades",
        "descripcion": "Mantenimiento de contactos con organismos reguladores y de aplicación de la ley.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Establecer procedimientos formales de contacto con autoridades y reguladores del sector.",
        "rec_media": "Identificar y documentar los organismos reguladores relevantes para el negocio.",
        "rec_baja": "Revisar anualmente los contactos con autoridades y actualizar el directorio.",
    },
    {
        "nombre": "ISO 27001 - 5.6 Contacto con grupos de interés especial",
        "descripcion": "Participación en foros y grupos especializados de seguridad de la información.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Unirse activamente a grupos ISAC y CERTs del sector para intercambio de inteligencia.",
        "rec_media": "Suscribirse a alertas de ciberseguridad y boletines de grupos especializados.",
        "rec_baja": "Revisar periódicamente la información recibida de los grupos de interés.",
    },
    {
        "nombre": "ISO 27001 - 5.7 Inteligencia de amenazas",
        "descripcion": "Recopilación y análisis de información sobre amenazas de seguridad relevantes.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar un proceso formal de inteligencia de amenazas con fuentes confiables (CTI).",
        "rec_media": "Suscribirse a feeds de amenazas y distribuir alertas pertinentes internamente.",
        "rec_baja": "Monitorear periódicamente las fuentes de noticias de ciberseguridad del sector.",
    },
    {
        "nombre": "ISO 27001 - 5.8 Seguridad de la información en la gestión de proyectos",
        "descripcion": "Integración de la seguridad en el ciclo de vida de los proyectos.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Incluir requisitos de seguridad como entregables obligatorios en todos los proyectos.",
        "rec_media": "Definir una lista de verificación de seguridad para la aprobación de proyectos.",
        "rec_baja": "Documentar las consideraciones de seguridad en las actas de inicio de proyecto.",
    },
    {
        "nombre": "ISO 27001 - 5.9 Inventario de activos de información",
        "descripcion": "Identificación y documentación de los activos de información y sus propietarios.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar una herramienta automatizada de inventario de activos con propietarios asignados.",
        "rec_media": "Crear y mantener un inventario manual de activos críticos actualizado trimestralmente.",
        "rec_baja": "Revisar y validar el inventario de activos al menos una vez al año.",
    },
    {
        "nombre": "ISO 27001 - 5.10 Uso aceptable de los activos de información",
        "descripcion": "Políticas y procedimientos para el uso correcto de los activos de información.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Publicar una política de uso aceptable firmada por todos los empleados anualmente.",
        "rec_media": "Actualizar la política de uso aceptable y comunicarla a todos los empleados.",
        "rec_baja": "Revisar el cumplimiento de la política de uso aceptable mediante auditorías spot.",
    },
    {
        "nombre": "ISO 27001 - 5.11 Devolución de activos",
        "descripcion": "Procedimientos para asegurar la devolución de activos al finalizar contratos.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar un proceso formal de offboarding con checklist de devolución de activos.",
        "rec_media": "Documentar y ejecutar el proceso de devolución de activos para toda desvinculación.",
        "rec_baja": "Verificar periódicamente que los activos asignados correspondan a empleados activos.",
    },
    {
        "nombre": "ISO 27001 - 5.12 Clasificación de la información",
        "descripcion": "Esquema de clasificación de la información según su criticidad y confidencialidad.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": False,
        "rec_alta": "Implementar un esquema de clasificación formal con etiquetado visible en todos los documentos.",
        "rec_media": "Definir categorías de clasificación y capacitar al personal en su aplicación.",
        "rec_baja": "Revisar la clasificación de los activos de información críticos anualmente.",
    },
    {
        "nombre": "ISO 27001 - 5.13 Etiquetado de la información",
        "descripcion": "Procedimientos para etiquetar la información de acuerdo con su clasificación.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": False,
        "rec_alta": "Automatizar el etiquetado de información mediante herramientas DLP integradas con el sistema.",
        "rec_media": "Establecer plantillas y convenciones de etiquetado para toda la documentación.",
        "rec_baja": "Auditar muestras de documentos para verificar el correcto etiquetado.",
    },
    {
        "nombre": "ISO 27001 - 5.14 Transferencia de información",
        "descripcion": "Controles para proteger la información durante su transferencia interna y externa.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar canales cifrados y políticas formales para toda transferencia de información sensible.",
        "rec_media": "Definir procedimientos de transferencia segura y capacitar a los empleados involucrados.",
        "rec_baja": "Revisar los acuerdos de confidencialidad con terceros que reciben información.",
    },
    {
        "nombre": "ISO 27001 - 5.15 Control de acceso",
        "descripcion": "Política y controles para regular el acceso a la información y sistemas.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar principio de mínimo privilegio y revisiones trimestrales de accesos.",
        "rec_media": "Documentar y revisar semianualmente los permisos de acceso por usuario y sistema.",
        "rec_baja": "Revisar anualmente los privilegios de acceso y eliminar los no utilizados.",
    },
    {
        "nombre": "ISO 27001 - 5.16 Gestión de identidades",
        "descripcion": "Control del ciclo de vida completo de identidades de usuarios y sistemas.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar un sistema IAM (Identity Access Management) con gestión automatizada del ciclo de vida.",
        "rec_media": "Establecer procedimientos documentados para alta, modificación y baja de identidades.",
        "rec_baja": "Revisar periódicamente cuentas inactivas o huérfanas y deshabilitarlas.",
    },
    {
        "nombre": "ISO 27001 - 5.17 Información de autenticación",
        "descripcion": "Gestión segura de credenciales de autenticación como contraseñas y tokens.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": False,
        "rec_alta": "Implementar gestores de contraseñas corporativos y políticas de complejidad robustas.",
        "rec_media": "Exigir cambio periódico de contraseñas y prohibir su reutilización.",
        "rec_baja": "Sensibilizar al personal sobre buenas prácticas de manejo de credenciales.",
    },
    {
        "nombre": "ISO 27001 - 5.18 Derechos de acceso",
        "descripcion": "Provisión, revisión, modificación y revocación de derechos de acceso.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Establecer procesos automatizados de aprovisionamiento y revocación de derechos de acceso.",
        "rec_media": "Documentar solicitudes, aprobaciones y revocaciones de acceso para auditoría.",
        "rec_baja": "Realizar revisiones de accesos al menos una vez al año.",
    },
    {
        "nombre": "ISO 27001 - 5.19 Seguridad de la información en relaciones con proveedores",
        "descripcion": "Gestión de riesgos de seguridad asociados a proveedores y terceros.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar un programa formal de gestión de riesgos de terceros con evaluaciones anuales.",
        "rec_media": "Incluir cláusulas de seguridad en todos los contratos con proveedores críticos.",
        "rec_baja": "Revisar periódicamente el cumplimiento de los requisitos de seguridad por proveedores.",
    },
    {
        "nombre": "ISO 27001 - 5.20 Seguridad de la información en acuerdos con proveedores",
        "descripcion": "Requisitos de seguridad formalizados en los contratos y acuerdos con proveedores.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Estandarizar cláusulas de seguridad obligatorias en todos los contratos de proveedores.",
        "rec_media": "Revisar y actualizar los contratos existentes para incluir requisitos de seguridad.",
        "rec_baja": "Verificar que los nuevos contratos incluyan al menos cláusulas básicas de confidencialidad.",
    },
    {
        "nombre": "ISO 27001 - 5.23 Seguridad de la información para uso de servicios en la nube",
        "descripcion": "Gestión de la seguridad en servicios de computación en la nube.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar una política de seguridad en la nube con controles de CASB y evaluación de proveedores.",
        "rec_media": "Documentar los servicios en la nube utilizados y los controles de seguridad aplicados.",
        "rec_baja": "Revisar los acuerdos de nivel de servicio (SLA) de los proveedores de nube.",
    },
    {
        "nombre": "ISO 27001 - 5.24 Planificación y preparación para la gestión de incidentes",
        "descripcion": "Preparación formal para responder a incidentes de seguridad de la información.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Desarrollar y probar un plan de respuesta a incidentes (IRP) con roles y procedimientos definidos.",
        "rec_media": "Documentar procedimientos básicos de respuesta a incidentes y comunicarlos al equipo.",
        "rec_baja": "Designar un responsable de respuesta a incidentes y establecer un canal de reporte.",
    },
    {
        "nombre": "ISO 27001 - 5.25 Evaluación y decisión sobre eventos de seguridad",
        "descripcion": "Proceso de triaje para determinar si un evento constituye un incidente de seguridad.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar criterios formales de clasificación de eventos con umbrales de escalamiento.",
        "rec_media": "Definir categorías de eventos de seguridad y procedimientos básicos de triaje.",
        "rec_baja": "Registrar todos los eventos de seguridad y revisarlos periódicamente.",
    },
    {
        "nombre": "ISO 27001 - 5.26 Respuesta a incidentes de seguridad de la información",
        "descripcion": "Procedimientos de respuesta, contención, erradicación y recuperación ante incidentes.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Contar con un equipo CSIRT dedicado y un playbook de respuesta para incidentes críticos.",
        "rec_media": "Establecer y practicar procedimientos de contención y erradicación de incidentes.",
        "rec_baja": "Documentar las acciones tomadas ante incidentes para aprendizaje organizacional.",
    },
    {
        "nombre": "ISO 27001 - 5.27 Aprendizaje de los incidentes de seguridad",
        "descripcion": "Análisis post-incidente para mejorar los controles de seguridad.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Realizar análisis de causa raíz (RCA) formales y publicar lecciones aprendidas.",
        "rec_media": "Documentar y revisar internamente las lecciones aprendidas de cada incidente.",
        "rec_baja": "Registrar los incidentes y revisar estadísticas para identificar patrones recurrentes.",
    },
    {
        "nombre": "ISO 27001 - 5.29 Seguridad de la información durante la disrupción",
        "descripcion": "Mantenimiento de la seguridad de la información durante situaciones de crisis o disrupción.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Integrar requisitos de seguridad en el plan de continuidad de negocio (BCP).",
        "rec_media": "Documentar medidas de seguridad para escenarios de contingencia.",
        "rec_baja": "Verificar que los procesos críticos mantengan controles básicos durante disrupciones.",
    },
    {
        "nombre": "ISO 27001 - 5.30 Preparación de las TIC para la continuidad del negocio",
        "descripcion": "Planificación de la disponibilidad de TIC para soportar la continuidad del negocio.",
        "dimensiones": 1,
        "activo": True,
        "confidencialidad": False,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar un plan de recuperación ante desastres (DRP) probado con RTO/RPO definidos.",
        "rec_media": "Documentar los requisitos de disponibilidad de TIC y establecer procedimientos de recuperación.",
        "rec_baja": "Revisar anualmente los planes de continuidad y los acuerdos de recuperación.",
    },
    # ── CATEGORÍA 6: CONTROLES DE PERSONAS ─────────────────────
    {
        "nombre": "ISO 27001 - 6.1 Investigación de antecedentes",
        "descripcion": "Verificación de antecedentes de candidatos antes de la contratación.",
        "dimensiones": 2,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": False,
        "rec_alta": "Implementar verificación de antecedentes completa (penal, crediticia, referencias) para todos los candidatos.",
        "rec_media": "Verificar referencias laborales y antecedentes penales para puestos con acceso a información sensible.",
        "rec_baja": "Solicitar referencias laborales básicas para todos los nuevos empleados.",
    },
    {
        "nombre": "ISO 27001 - 6.2 Términos y condiciones de empleo",
        "descripcion": "Inclusión de obligaciones de seguridad en los contratos laborales.",
        "dimensiones": 2,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": False,
        "rec_alta": "Incluir cláusulas detalladas de confidencialidad y seguridad en todos los contratos laborales.",
        "rec_media": "Actualizar los contratos existentes para incluir obligaciones de seguridad de la información.",
        "rec_baja": "Asegurar que todos los contratos nuevos incluyan cláusulas básicas de confidencialidad.",
    },
    {
        "nombre": "ISO 27001 - 6.3 Concienciación, educación y formación en seguridad",
        "descripcion": "Programa de capacitación y concienciación en seguridad para todo el personal.",
        "dimensiones": 2,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar un programa formal de concienciación con simulacros de phishing y métricas de efectividad.",
        "rec_media": "Realizar capacitaciones de seguridad al menos una vez al año para todo el personal.",
        "rec_baja": "Distribuir material informativo básico sobre seguridad a todos los empleados.",
    },
    {
        "nombre": "ISO 27001 - 6.4 Proceso disciplinario",
        "descripcion": "Procedimientos formales para sancionar incumplimientos de políticas de seguridad.",
        "dimensiones": 2,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": False,
        "rec_alta": "Establecer un proceso disciplinario formal documentado y comunicado a todo el personal.",
        "rec_media": "Documentar las consecuencias del incumplimiento de políticas de seguridad en el reglamento interno.",
        "rec_baja": "Incluir en la inducción las consecuencias del incumplimiento de políticas de seguridad.",
    },
    {
        "nombre": "ISO 27001 - 6.5 Responsabilidades tras el cese o cambio de empleo",
        "descripcion": "Gestión de obligaciones de seguridad al finalizar o cambiar el empleo.",
        "dimensiones": 2,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar un proceso de offboarding que incluya revocación inmediata de accesos y devolución de activos.",
        "rec_media": "Documentar y ejecutar un checklist de desvinculación para todos los casos de cese.",
        "rec_baja": "Verificar la devolución de activos y cierre de cuentas al terminar cada contrato.",
    },
    {
        "nombre": "ISO 27001 - 6.6 Acuerdos de confidencialidad y no divulgación",
        "descripcion": "Firma de acuerdos de confidencialidad con empleados y terceros.",
        "dimensiones": 2,
        "activo": True,
        "confidencialidad": True,
        "integridad": False,
        "disponibilidad": False,
        "rec_alta": "Implementar acuerdos de confidencialidad (NDA) robustos con revisión jurídica periódica.",
        "rec_media": "Asegurar que todos los empleados y contratistas firmen acuerdos de confidencialidad.",
        "rec_baja": "Incluir cláusulas de confidencialidad básicas en los contratos de trabajo.",
    },
    {
        "nombre": "ISO 27001 - 6.7 Trabajo remoto",
        "descripcion": "Controles para proteger la información cuando los empleados trabajan de forma remota.",
        "dimensiones": 2,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar política de teletrabajo con VPN obligatoria, cifrado de disco y controles de endpoint.",
        "rec_media": "Establecer guías de seguridad para el trabajo remoto y VPN para acceso a sistemas críticos.",
        "rec_baja": "Comunicar recomendaciones básicas de seguridad para el trabajo desde casa.",
    },
    {
        "nombre": "ISO 27001 - 6.8 Reporte de eventos de seguridad de la información",
        "descripcion": "Mecanismos para que el personal reporte eventos y debilidades de seguridad.",
        "dimensiones": 2,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Establecer un canal anónimo de reporte 24/7 con SLA de respuesta documentado.",
        "rec_media": "Comunicar al personal cómo y a quién reportar eventos de seguridad.",
        "rec_baja": "Designar un responsable de recibir reportes de seguridad del personal.",
    },
    # ── CATEGORÍA 7: CONTROLES FÍSICOS ───────────────────────────
    {
        "nombre": "ISO 27001 - 7.1 Perímetros de seguridad física",
        "descripcion": "Definición de perímetros físicos para proteger áreas que contienen información.",
        "dimensiones": 3,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar múltiples perímetros de seguridad con controles de acceso biométrico.",
        "rec_media": "Establecer zonas restringidas claramente delimitadas con control de acceso por tarjeta.",
        "rec_baja": "Asegurar que las áreas con información sensible tengan acceso controlado.",
    },
    {
        "nombre": "ISO 27001 - 7.2 Controles físicos de entrada",
        "descripcion": "Controles para asegurar que solo el personal autorizado accede a las instalaciones.",
        "dimensiones": 3,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar control de acceso con lectores biométricos, cámaras y registro de accesos.",
        "rec_media": "Utilizar tarjetas de acceso y registrar el ingreso a áreas sensibles.",
        "rec_baja": "Controlar el acceso de visitantes mediante registro manual y acompañamiento.",
    },
    {
        "nombre": "ISO 27001 - 7.3 Seguridad de oficinas, despachos e instalaciones",
        "descripcion": "Medidas de seguridad física para proteger las instalaciones de la organización.",
        "dimensiones": 3,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar controles físicos completos: cerraduras de seguridad, alarmas y CCTV.",
        "rec_media": "Asegurar que las áreas con información crítica tengan cerraduras y acceso controlado.",
        "rec_baja": "Mantener las áreas de trabajo ordenadas y proteger documentos sensibles bajo llave.",
    },
    {
        "nombre": "ISO 27001 - 7.4 Supervisión de la seguridad física",
        "descripcion": "Monitoreo continuo de las instalaciones para detectar accesos no autorizados.",
        "dimensiones": 3,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar CCTV con monitoreo 24/7 y alertas automáticas de intrusión.",
        "rec_media": "Instalar cámaras en áreas críticas y revisar grabaciones periódicamente.",
        "rec_baja": "Realizar rondas de seguridad física periódicas en las instalaciones.",
    },
    {
        "nombre": "ISO 27001 - 7.5 Protección contra amenazas físicas y ambientales",
        "descripcion": "Medidas de protección contra desastres naturales, incendios, inundaciones y otros.",
        "dimensiones": 3,
        "activo": True,
        "confidencialidad": False,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar sistemas contra incendios, control de temperatura y detectores de inundación.",
        "rec_media": "Instalar extintores y sistemas de detección de incendios en áreas con equipos críticos.",
        "rec_baja": "Verificar que los equipos críticos estén alejados de riesgos ambientales obvios.",
    },
    {
        "nombre": "ISO 27001 - 7.6 Trabajo en áreas seguras",
        "descripcion": "Procedimientos y controles para el trabajo en zonas de seguridad física.",
        "dimensiones": 3,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": False,
        "rec_alta": "Establecer procedimientos estrictos para trabajo en áreas seguras con supervisión.",
        "rec_media": "Documentar los procedimientos de acceso y trabajo en áreas de seguridad.",
        "rec_baja": "Asegurar que el trabajo en áreas sensibles requiera autorización previa.",
    },
    {
        "nombre": "ISO 27001 - 7.7 Escritorio y pantalla limpios",
        "descripcion": "Política de escritorio limpio para proteger información fuera del horario laboral.",
        "dimensiones": 3,
        "activo": True,
        "confidencialidad": True,
        "integridad": False,
        "disponibilidad": False,
        "rec_alta": "Implementar auditorías de cumplimiento de política de escritorio limpio con seguimiento.",
        "rec_media": "Comunicar y exigir el cumplimiento de la política de escritorio y pantalla limpios.",
        "rec_baja": "Sensibilizar al personal sobre la importancia de asegurar documentos al ausentarse.",
    },
    {
        "nombre": "ISO 27001 - 7.8 Ubicación y protección de equipos",
        "descripcion": "Selección y protección de la ubicación física de los equipos de procesamiento.",
        "dimensiones": 3,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Ubicar los equipos críticos en áreas con control ambiental y acceso restringido.",
        "rec_media": "Asegurar que los equipos de procesamiento estén protegidos de daños físicos y ambientales.",
        "rec_baja": "Verificar periódicamente las condiciones físicas de los equipos críticos.",
    },
    {
        "nombre": "ISO 27001 - 7.9 Seguridad de los activos fuera de las instalaciones",
        "descripcion": "Protección de equipos y activos utilizados fuera de las instalaciones.",
        "dimensiones": 3,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar cifrado de disco completo y MDM para todos los dispositivos móviles corporativos.",
        "rec_media": "Establecer política de uso de dispositivos fuera de las instalaciones con cifrado obligatorio.",
        "rec_baja": "Sensibilizar al personal sobre los riesgos de seguridad de los activos fuera de la empresa.",
    },
    {
        "nombre": "ISO 27001 - 7.10 Medios de almacenamiento",
        "descripcion": "Gestión segura del ciclo de vida de los medios de almacenamiento de información.",
        "dimensiones": 3,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar procedimientos de borrado seguro certificado y destrucción física de medios.",
        "rec_media": "Establecer un inventario de medios de almacenamiento y procedimientos de eliminación segura.",
        "rec_baja": "Asegurar que los medios con información sensible sean eliminados de forma que no sea recuperable.",
    },
    {
        "nombre": "ISO 27001 - 7.11 Servicios de suministro",
        "descripcion": "Protección de la infraestructura de suministro eléctrico y otros servicios esenciales.",
        "dimensiones": 3,
        "activo": True,
        "confidencialidad": False,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar UPS, generadores de respaldo y monitoreo de suministros con alertas.",
        "rec_media": "Instalar UPS para equipos críticos y revisar periódicamente los sistemas de respaldo.",
        "rec_baja": "Verificar la disponibilidad de fuentes alternativas de suministro eléctrico.",
    },
    {
        "nombre": "ISO 27001 - 7.12 Seguridad del cableado",
        "descripcion": "Protección del cableado de energía y telecomunicaciones contra interferencias o daños.",
        "dimensiones": 3,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar cableado estructurado documentado con protección física en áreas críticas.",
        "rec_media": "Asegurar que el cableado crítico esté protegido y documentado.",
        "rec_baja": "Verificar periódicamente el estado del cableado en áreas de procesamiento.",
    },
    {
        "nombre": "ISO 27001 - 7.13 Mantenimiento de equipos",
        "descripcion": "Procedimientos de mantenimiento preventivo y correctivo de equipos de procesamiento.",
        "dimensiones": 3,
        "activo": True,
        "confidencialidad": False,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar un programa de mantenimiento preventivo calendarizado con registros.",
        "rec_media": "Establecer procedimientos de mantenimiento y documentar los trabajos realizados.",
        "rec_baja": "Realizar mantenimiento correctivo ante fallas y registrar las intervenciones.",
    },
    {
        "nombre": "ISO 27001 - 7.14 Eliminación o reutilización segura de equipos",
        "descripcion": "Asegurar la eliminación segura de información antes de desechar o reutilizar equipos.",
        "dimensiones": 3,
        "activo": True,
        "confidencialidad": True,
        "integridad": False,
        "disponibilidad": False,
        "rec_alta": "Implementar procedimientos certificados de sanitización de datos según estándares (DoD, NIST).",
        "rec_media": "Establecer un proceso documentado de borrado seguro antes de desechar o reasignar equipos.",
        "rec_baja": "Verificar que los equipos dados de baja no contengan información sensible.",
    },
    # ── CATEGORÍA 8: CONTROLES TECNOLÓGICOS ───────────────────────
    {
        "nombre": "ISO 27001 - 8.1 Dispositivos de usuario final",
        "descripcion": "Protección de la información procesada, almacenada o transmitida en dispositivos de usuario.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar MDM con cifrado, bloqueo remoto y gestión de aplicaciones para todos los dispositivos.",
        "rec_media": "Establecer políticas de seguridad de endpoint con antivirus y actualizaciones automáticas.",
        "rec_baja": "Asegurar que los dispositivos corporativos tengan antivirus y contraseña de bloqueo.",
    },
    {
        "nombre": "ISO 27001 - 8.2 Derechos de acceso privilegiado",
        "descripcion": "Control estricto de cuentas y accesos con privilegios elevados.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar PAM (Privileged Access Management) con grabación de sesiones y MFA obligatorio.",
        "rec_media": "Limitar y documentar el acceso privilegiado con revisiones trimestrales.",
        "rec_baja": "Revisar periódicamente quién tiene acceso privilegiado y eliminar los innecesarios.",
    },
    {
        "nombre": "ISO 27001 - 8.3 Restricción de acceso a la información",
        "descripcion": "Controles para limitar el acceso a sistemas y datos según necesidad de conocimiento.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": False,
        "rec_alta": "Implementar control de acceso basado en roles (RBAC) con revisiones periódicas automatizadas.",
        "rec_media": "Documentar y aplicar controles de acceso basados en el principio de mínimo privilegio.",
        "rec_baja": "Revisar periódicamente los permisos de acceso y eliminar los no utilizados.",
    },
    {
        "nombre": "ISO 27001 - 8.4 Acceso al código fuente",
        "descripcion": "Control de acceso al código fuente, herramientas de desarrollo y bibliotecas.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": False,
        "rec_alta": "Implementar repositorios con control de versiones, revisión de código obligatoria y auditoría de accesos.",
        "rec_media": "Restringir el acceso al código fuente a los desarrolladores autorizados y usar repositorios controlados.",
        "rec_baja": "Asegurar que el código fuente esté almacenado en repositorios protegidos por contraseña.",
    },
    {
        "nombre": "ISO 27001 - 8.5 Autenticación segura",
        "descripcion": "Implementación de mecanismos robustos de autenticación para acceso a sistemas.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": False,
        "rec_alta": "Implementar MFA en todos los sistemas críticos y SSO corporativo con control centralizado.",
        "rec_media": "Habilitar autenticación de dos factores (2FA) en sistemas con información sensible.",
        "rec_baja": "Exigir contraseñas robustas y cambios periódicos en todos los sistemas.",
    },
    {
        "nombre": "ISO 27001 - 8.6 Gestión de capacidad",
        "descripcion": "Monitoreo y planificación de la capacidad de los recursos de TI.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": False,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar monitoreo automatizado de capacidad con alertas y proyecciones de crecimiento.",
        "rec_media": "Monitorear regularmente el uso de recursos y planificar ampliaciones con anticipación.",
        "rec_baja": "Revisar periódicamente el uso de almacenamiento y procesamiento de sistemas críticos.",
    },
    {
        "nombre": "ISO 27001 - 8.7 Protección contra malware",
        "descripcion": "Controles técnicos y de concientización para proteger contra código malicioso.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar EDR con detección basada en comportamiento y respuesta automatizada.",
        "rec_media": "Instalar y mantener actualizado antivirus/antimalware en todos los equipos.",
        "rec_baja": "Asegurar que todos los equipos tengan software antivirus activo y actualizado.",
    },
    {
        "nombre": "ISO 27001 - 8.8 Gestión de vulnerabilidades técnicas",
        "descripcion": "Identificación y remediación oportuna de vulnerabilidades técnicas en sistemas.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar un programa de gestión de vulnerabilidades con escaneo continuo y SLA de parchado.",
        "rec_media": "Realizar escaneos de vulnerabilidades trimestrales y parchado según criticidad.",
        "rec_baja": "Aplicar parches de seguridad críticos dentro de los 30 días de su publicación.",
    },
    {
        "nombre": "ISO 27001 - 8.9 Gestión de la configuración",
        "descripcion": "Establecimiento y mantenimiento de configuraciones seguras de sistemas y equipos.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar gestión de configuración con IaC, líneas base de seguridad y control de cambios.",
        "rec_media": "Documentar y aplicar configuraciones base seguras para todos los sistemas.",
        "rec_baja": "Verificar que los sistemas críticos no tengan configuraciones por defecto sin cambiar.",
    },
    {
        "nombre": "ISO 27001 - 8.10 Eliminación de información",
        "descripcion": "Eliminación segura de información cuando ya no es necesaria.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": False,
        "disponibilidad": False,
        "rec_alta": "Implementar políticas de retención y eliminación de datos con herramientas certificadas.",
        "rec_media": "Establecer procedimientos de eliminación segura de información según su clasificación.",
        "rec_baja": "Asegurar que la información sensible sea eliminada de forma irreversible al finalizar su uso.",
    },
    {
        "nombre": "ISO 27001 - 8.11 Enmascaramiento de datos",
        "descripcion": "Técnicas de enmascaramiento para proteger datos sensibles en entornos no productivos.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": False,
        "disponibilidad": False,
        "rec_alta": "Implementar enmascaramiento dinámico y estático de datos en entornos de desarrollo y pruebas.",
        "rec_media": "Usar datos anonimizados o enmascarados en ambientes de prueba y desarrollo.",
        "rec_baja": "Verificar que los entornos de prueba no utilicen datos reales sin anonimizar.",
    },
    {
        "nombre": "ISO 27001 - 8.12 Prevención de fuga de datos (DLP)",
        "descripcion": "Controles para prevenir la divulgación no autorizada de información sensible.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": False,
        "disponibilidad": False,
        "rec_alta": "Implementar solución DLP en red, endpoint y nube con políticas adaptadas a la clasificación.",
        "rec_media": "Implementar controles básicos DLP para canales de mayor riesgo (email, USB, nube).",
        "rec_baja": "Sensibilizar al personal sobre los riesgos de fuga de información.",
    },
    {
        "nombre": "ISO 27001 - 8.13 Respaldo de la información",
        "descripcion": "Copias de seguridad regulares y verificadas de la información y sistemas.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar respaldos automáticos con política 3-2-1, cifrado y pruebas de restauración mensuales.",
        "rec_media": "Realizar respaldos regulares con verificación de integridad y almacenamiento offsite.",
        "rec_baja": "Realizar respaldos periódicos y verificar ocasionalmente que sean restaurables.",
    },
    {
        "nombre": "ISO 27001 - 8.14 Redundancia de instalaciones de procesamiento",
        "descripcion": "Implementación de redundancia para garantizar la disponibilidad continua.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": False,
        "integridad": False,
        "disponibilidad": True,
        "rec_alta": "Implementar arquitectura de alta disponibilidad con failover automático y sin punto único de fallo.",
        "rec_media": "Implementar redundancia para sistemas críticos con procedimientos de failover documentados.",
        "rec_baja": "Identificar los sistemas sin redundancia y evaluar el impacto de su falla.",
    },
    {
        "nombre": "ISO 27001 - 8.15 Registro de actividades (Logging)",
        "descripcion": "Generación, almacenamiento y protección de registros de actividad del sistema.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar SIEM con correlación de eventos, alertas en tiempo real y retención de logs de 1 año.",
        "rec_media": "Centralizar logs de sistemas críticos y establecer un período de retención mínimo.",
        "rec_baja": "Asegurar que los sistemas críticos generen logs de acceso y errores.",
    },
    {
        "nombre": "ISO 27001 - 8.16 Actividades de monitoreo",
        "descripcion": "Monitoreo continuo de redes, sistemas y comportamiento de usuarios.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar un SOC con monitoreo 24/7, detección de anomalías y respuesta automatizada.",
        "rec_media": "Monitorear activamente los sistemas críticos y revisar alertas de seguridad diariamente.",
        "rec_baja": "Revisar periódicamente los logs de seguridad de los sistemas más críticos.",
    },
    {
        "nombre": "ISO 27001 - 8.17 Sincronización de relojes",
        "descripcion": "Sincronización de relojes de todos los sistemas para correlación de eventos.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": False,
        "integridad": True,
        "disponibilidad": False,
        "rec_alta": "Implementar NTP centralizado con monitoreo de sincronización y alertas de desviación.",
        "rec_media": "Configurar NTP en todos los sistemas para sincronización con fuentes confiables.",
        "rec_baja": "Verificar que los sistemas críticos tengan sus relojes sincronizados correctamente.",
    },
    {
        "nombre": "ISO 27001 - 8.18 Uso de programas utilitarios con privilegios",
        "descripcion": "Control del uso de herramientas del sistema que pueden eludir controles de seguridad.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar listas blancas de aplicaciones y controlar el uso de utilidades privilegiadas.",
        "rec_media": "Restringir y registrar el uso de herramientas del sistema con privilegios elevados.",
        "rec_baja": "Documentar qué herramientas utilitarias privilegiadas están permitidas y por quién.",
    },
    {
        "nombre": "ISO 27001 - 8.19 Instalación de software en sistemas en producción",
        "descripcion": "Control sobre la instalación de software en sistemas operativos de producción.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar listas blancas de software y un proceso formal de aprobación de instalaciones.",
        "rec_media": "Establecer un proceso de aprobación para la instalación de software en producción.",
        "rec_baja": "Prohibir la instalación de software no autorizado en sistemas de producción.",
    },
    {
        "nombre": "ISO 27001 - 8.20 Seguridad de redes",
        "descripcion": "Controles para proteger la infraestructura de red y los datos que transita.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar segmentación de red, IDS/IPS, firewall de próxima generación y monitoreo continuo.",
        "rec_media": "Implementar firewalls, segmentación básica de red y monitoreo de tráfico sospechoso.",
        "rec_baja": "Asegurar que la red esté protegida por firewall con reglas actualizadas.",
    },
    {
        "nombre": "ISO 27001 - 8.21 Seguridad de los servicios de red",
        "descripcion": "Mecanismos de seguridad y controles para servicios de red internos y externos.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Documentar, inventariar y proteger todos los servicios de red con controles adecuados a su criticidad.",
        "rec_media": "Identificar los servicios de red expuestos y aplicar controles de seguridad básicos.",
        "rec_baja": "Revisar periódicamente los servicios de red activos y deshabilitar los innecesarios.",
    },
    {
        "nombre": "ISO 27001 - 8.22 Separación de redes",
        "descripcion": "Segmentación de redes para aislar grupos de sistemas y servicios.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar microsegmentación con políticas de firewall entre todos los segmentos de red.",
        "rec_media": "Separar la red de producción de la de desarrollo y usuarios mediante VLANs.",
        "rec_baja": "Aislar al menos la red de servidores críticos de la red de usuarios generales.",
    },
    {
        "nombre": "ISO 27001 - 8.23 Filtrado web",
        "descripcion": "Controles de filtrado de acceso a recursos web externos.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": False,
        "rec_alta": "Implementar proxy web con categorización, filtrado de malware y reportes de actividad.",
        "rec_media": "Implementar filtrado web para bloquear categorías de alto riesgo (malware, phishing).",
        "rec_baja": "Establecer una política de uso aceptable de internet y comunicarla al personal.",
    },
    {
        "nombre": "ISO 27001 - 8.24 Uso de criptografía",
        "descripcion": "Políticas y controles para el uso efectivo de criptografía.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": False,
        "rec_alta": "Implementar política criptográfica con estándares actualizados, gestión de claves y revisión periódica.",
        "rec_media": "Establecer y documentar los algoritmos criptográficos permitidos y gestión de claves.",
        "rec_baja": "Verificar que la información sensible esté cifrada en tránsito y en reposo.",
    },
    {
        "nombre": "ISO 27001 - 8.25 Ciclo de vida de desarrollo seguro",
        "descripcion": "Integración de la seguridad en todas las etapas del ciclo de desarrollo de software.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar DevSecOps con análisis SAST/DAST, revisión de código y gates de seguridad en CI/CD.",
        "rec_media": "Incluir revisión de seguridad en el proceso de desarrollo y pruebas de penetración periódicas.",
        "rec_baja": "Capacitar a los desarrolladores en prácticas básicas de codificación segura.",
    },
    {
        "nombre": "ISO 27001 - 8.26 Requisitos de seguridad de aplicaciones",
        "descripcion": "Identificación y especificación de requisitos de seguridad para nuevas aplicaciones.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar un proceso formal de análisis de requisitos de seguridad (threat modeling) para cada app.",
        "rec_media": "Documentar requisitos de seguridad mínimos para nuevas aplicaciones y verificar su cumplimiento.",
        "rec_baja": "Incluir consideraciones de seguridad básicas al definir requisitos de nuevas aplicaciones.",
    },
    {
        "nombre": "ISO 27001 - 8.28 Codificación segura",
        "descripcion": "Aplicación de principios y prácticas de programación segura en el desarrollo.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar guías de codificación segura basadas en OWASP y revisiones de código obligatorias.",
        "rec_media": "Establecer estándares de codificación segura y capacitar a los desarrolladores en OWASP Top 10.",
        "rec_baja": "Sensibilizar a los desarrolladores sobre las vulnerabilidades más comunes (inyección, XSS).",
    },
    {
        "nombre": "ISO 27001 - 8.29 Pruebas de seguridad en desarrollo y aceptación",
        "descripcion": "Pruebas de seguridad integradas en los procesos de desarrollo y aceptación.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar pruebas de seguridad automatizadas (SAST/DAST) en el pipeline CI/CD.",
        "rec_media": "Realizar pruebas de seguridad manuales antes de poner en producción aplicaciones críticas.",
        "rec_baja": "Incluir casos de prueba de seguridad básica en el proceso de QA.",
    },
    {
        "nombre": "ISO 27001 - 8.30 Outsourcing del desarrollo",
        "descripcion": "Gestión de la seguridad en el desarrollo de software externalizado.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": False,
        "rec_alta": "Auditar las prácticas de seguridad de los proveedores de desarrollo externalizados.",
        "rec_media": "Incluir requisitos de seguridad en los contratos de desarrollo externalizado.",
        "rec_baja": "Revisar el código entregado por proveedores externos antes de su despliegue.",
    },
    {
        "nombre": "ISO 27001 - 8.31 Separación de entornos de desarrollo, pruebas y producción",
        "descripcion": "Aislamiento de los entornos de desarrollo, pruebas y producción.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar entornos completamente separados con datos de prueba sintéticos y accesos diferenciados.",
        "rec_media": "Separar los entornos de desarrollo, pruebas y producción con accesos diferenciados.",
        "rec_baja": "Asegurar que los cambios sean probados en un entorno separado antes de producción.",
    },
    {
        "nombre": "ISO 27001 - 8.32 Gestión de cambios",
        "descripcion": "Procedimientos formales para gestionar cambios en sistemas y aplicaciones.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Implementar un proceso formal de gestión de cambios con aprobación, pruebas y plan de rollback.",
        "rec_media": "Establecer un proceso básico de control de cambios con registro y aprobación.",
        "rec_baja": "Documentar los cambios realizados en sistemas de producción.",
    },
    {
        "nombre": "ISO 27001 - 8.33 Información de pruebas",
        "descripcion": "Selección, protección y gestión de la información utilizada para pruebas.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": False,
        "rec_alta": "Prohibir el uso de datos reales en pruebas y usar datos sintéticos generados automáticamente.",
        "rec_media": "Anonimizar los datos de producción antes de utilizarlos en entornos de prueba.",
        "rec_baja": "Evitar usar información personal real en los entornos de prueba.",
    },
    {
        "nombre": "ISO 27001 - 8.34 Protección de los sistemas de información durante las auditorías",
        "descripcion": "Protección de los sistemas durante las actividades de auditoría y acceso de terceros.",
        "dimensiones": 4,
        "activo": True,
        "confidencialidad": True,
        "integridad": True,
        "disponibilidad": True,
        "rec_alta": "Planificar auditorías con alcance definido, supervisión continua y herramientas de solo lectura.",
        "rec_media": "Coordinar las auditorías con el equipo de TI para minimizar el impacto en la operación.",
        "rec_baja": "Registrar y supervisar las actividades de los auditores durante su acceso a sistemas.",
    },
]
